FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Clean install dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Start the development server
CMD ["npm", "run", "dev", "--", "--host"]

EXPOSE 5173